development:
  adapter: postgresql
  database: votes-development

test:
  adapter: postgresql
  database: votes-test

production:
  adapter: postgresql
  database: votes-production
  url: <%= ENV['DATABASE_URL']%>
